<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <!-- Main project dependencies -->
        <PackageVersion Include="PanoramicData.NCalcExtensions" Version="5.8.53" />

        <!-- Test project dependencies -->
        <PackageVersion Include="AwesomeAssertions" Version="9.4.0" />
        <PackageVersion Include="AwesomeAssertions.Analyzers" Version="9.0.8" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
        <PackageVersion Include="xunit.v3" Version="3.2.2" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageVersion Include="coverlet.collector" Version="8.0.1" />
        <PackageVersion Include="Xunit.Microsoft.DependencyInjection" Version="10.0.4" />

        <!-- Build tooling -->
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.9.50" />
    </ItemGroup>
</Project>
