<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<LangVersion>latest</LangVersion>
	<ApplicationIcon>Icon.ico</ApplicationIcon>
	<PackageProjectUrl>https://github.com/panoramicdata/PanoramicData.Vtl/</PackageProjectUrl>
	<PackageLicenseUrl></PackageLicenseUrl>
	<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	<PackageIcon>Icon.png</PackageIcon>
	<PackageTags>VTL Library</PackageTags>
	<Title>PanoramicData.Vtl</Title>
	<Description>A .NET library for the Velocity Template Language (VTL)</Description>
	<Summary>A .NET library for the Velocity Template Language (VTL)</Summary>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/panoramicdata/PanoramicData.Vtl/</RepositoryUrl>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>

	<PackageReleaseNotes>Moved to net10.0</PackageReleaseNotes>

</PropertyGroup>

<ItemGroup>
  <PackageReference Include="PanoramicData.NCalcExtensions" />
</ItemGroup>
	<ItemGroup>
		<None Include="Icon.png" Pack="true" PackagePath="" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Update="Nerdbank.GitVersioning" />
	</ItemGroup>
</Project>
